///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace rx_git_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("879387ae-bc61-4657-b24d-1aba3483e35d", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the rx_git_projRepository repository.
        /// </summary>
        public static rx_git_projRepository repo = rx_git_projRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Website", "Opening web site 'http://opensource.demo.orangehrmlive.com/' with browser 'chrome' in normal mode.", new RecordItemIndex(0));
            Host.Current.OpenBrowser("http://opensource.demo.orangehrmlive.com/", "chrome", "", false, false, false, false, false);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRMGoogleChrome.Element1747682544' at 850;202.", repo.OrangeHRMGoogleChrome.Element1747682544Info, new RecordItemIndex(1));
            repo.OrangeHRMGoogleChrome.Element1747682544.Click("850;202");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRMGoogleChrome.Element1747682544' at 757;335.", repo.OrangeHRMGoogleChrome.Element1747682544Info, new RecordItemIndex(2));
            repo.OrangeHRMGoogleChrome.Element1747682544.Click("757;335");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRMGoogleChrome.Element1747682544' at 753;351.", repo.OrangeHRMGoogleChrome.Element1747682544Info, new RecordItemIndex(3));
            repo.OrangeHRMGoogleChrome.Element1747682544.Click("753;351");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Admin' with focus on 'OrangeHRMGoogleChrome'.", repo.OrangeHRMGoogleChrome.SelfInfo, new RecordItemIndex(4));
            repo.OrangeHRMGoogleChrome.Self.PressKeys("Admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRMGoogleChrome.Element1747682544' at 749;399.", repo.OrangeHRMGoogleChrome.Element1747682544Info, new RecordItemIndex(5));
            repo.OrangeHRMGoogleChrome.Element1747682544.Click("749;399");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'admin' with focus on 'OrangeHRMGoogleChrome'.", repo.OrangeHRMGoogleChrome.SelfInfo, new RecordItemIndex(6));
            repo.OrangeHRMGoogleChrome.Self.PressKeys("admin");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRMGoogleChrome.Element1747682544' at 725;456.", repo.OrangeHRMGoogleChrome.Element1747682544Info, new RecordItemIndex(7));
            repo.OrangeHRMGoogleChrome.Element1747682544.Click("725;456");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRMGoogleChrome.OrangeHRM' at 35;9.", repo.OrangeHRMGoogleChrome.OrangeHRMInfo, new RecordItemIndex(8));
            repo.OrangeHRMGoogleChrome.OrangeHRM.Click("35;9");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OrangeHRMGoogleChrome.Element1614894656' at 748;345.", repo.OrangeHRMGoogleChrome.Element1614894656Info, new RecordItemIndex(9));
            repo.OrangeHRMGoogleChrome.Element1614894656.DoubleClick("748;345");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Dropdown' at 63;8.", repo.Dropdown.SelfInfo, new RecordItemIndex(10));
            repo.Dropdown.Self.Click("63;8");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OrangeHRMGoogleChrome.Element1614894656' at 739;383.", repo.OrangeHRMGoogleChrome.Element1614894656Info, new RecordItemIndex(11));
            repo.OrangeHRMGoogleChrome.Element1614894656.DoubleClick("739;383");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'OrangeHRMGoogleChrome.Element1614894656' at 734;397.", repo.OrangeHRMGoogleChrome.Element1614894656Info, new RecordItemIndex(12));
            repo.OrangeHRMGoogleChrome.Element1614894656.DoubleClick("734;397");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'OrangeHRMGoogleChrome.Element1614894656' at 726;447.", repo.OrangeHRMGoogleChrome.Element1614894656Info, new RecordItemIndex(13));
            repo.OrangeHRMGoogleChrome.Element1614894656.Click("726;447");
            Delay.Milliseconds(200);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
