///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace rx_git_proj
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the rx_git_projRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    [RepositoryFolder("3bb2f438-907a-4521-bf73-d81f0bde6e92")]
    public partial class rx_git_projRepository : RepoGenBaseFolder
    {
        static rx_git_projRepository instance = new rx_git_projRepository();
        rx_git_projRepositoryFolders.OrangeHRMGoogleChromeAppFolder _orangehrmgooglechrome;
        rx_git_projRepositoryFolders.DropdownAppFolder _dropdown;
        rx_git_projRepositoryFolders.HRManagementSystemOrangeHRMLHRMaAppFolder _hrmanagementsystemorangehrmlhrma;
        RepoItemInfo _professionalhrmquoterequestatoranInfo;

        /// <summary>
        /// Gets the singleton class instance representing the rx_git_projRepository element repository.
        /// </summary>
        [RepositoryFolder("3bb2f438-907a-4521-bf73-d81f0bde6e92")]
        public static rx_git_projRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public rx_git_projRepository() 
            : base("rx_git_projRepository", "/", null, 0, false, "3bb2f438-907a-4521-bf73-d81f0bde6e92", ".\\RepositoryImages\\rx_git_projRepository3bb2f438.rximgres")
        {
            _orangehrmgooglechrome = new rx_git_projRepositoryFolders.OrangeHRMGoogleChromeAppFolder(this);
            _dropdown = new rx_git_projRepositoryFolders.DropdownAppFolder(this);
            _hrmanagementsystemorangehrmlhrma = new rx_git_projRepositoryFolders.HRManagementSystemOrangeHRMLHRMaAppFolder(this);
            _professionalhrmquoterequestatoranInfo = new RepoItemInfo(this, "ProfessionalHRMQuoteRequestAtOran", "/form[@title~'^Professional\\ HRM\\ \\|\\ Quote\\ ']", 30000, null, "223c820f-4cae-427f-92bd-f5216ba0fa09");
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("3bb2f438-907a-4521-bf73-d81f0bde6e92")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ProfessionalHRMQuoteRequestAtOran item.
        /// </summary>
        [RepositoryItem("223c820f-4cae-427f-92bd-f5216ba0fa09")]
        public virtual Ranorex.Form ProfessionalHRMQuoteRequestAtOran
        {
            get
            {
                 return _professionalhrmquoterequestatoranInfo.CreateAdapter<Ranorex.Form>(true);
            }
        }

        /// <summary>
        /// The ProfessionalHRMQuoteRequestAtOran item info.
        /// </summary>
        [RepositoryItemInfo("223c820f-4cae-427f-92bd-f5216ba0fa09")]
        public virtual RepoItemInfo ProfessionalHRMQuoteRequestAtOranInfo
        {
            get
            {
                return _professionalhrmquoterequestatoranInfo;
            }
        }

        /// <summary>
        /// The OrangeHRMGoogleChrome folder.
        /// </summary>
        [RepositoryFolder("888a87c5-9591-4fea-86cc-f6151953c5a7")]
        public virtual rx_git_projRepositoryFolders.OrangeHRMGoogleChromeAppFolder OrangeHRMGoogleChrome
        {
            get { return _orangehrmgooglechrome; }
        }

        /// <summary>
        /// The Dropdown folder.
        /// </summary>
        [RepositoryFolder("75f53e42-e22e-422d-82c1-8ea4dd4b48d3")]
        public virtual rx_git_projRepositoryFolders.DropdownAppFolder Dropdown
        {
            get { return _dropdown; }
        }

        /// <summary>
        /// The HRManagementSystemOrangeHRMLHRMa folder.
        /// </summary>
        [RepositoryFolder("c6feec1a-d49f-4fc7-9241-4e6d71d6e437")]
        public virtual rx_git_projRepositoryFolders.HRManagementSystemOrangeHRMLHRMaAppFolder HRManagementSystemOrangeHRMLHRMa
        {
            get { return _hrmanagementsystemorangehrmlhrma; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.1")]
    public partial class rx_git_projRepositoryFolders
    {
        /// <summary>
        /// The OrangeHRMGoogleChromeAppFolder folder.
        /// </summary>
        [RepositoryFolder("888a87c5-9591-4fea-86cc-f6151953c5a7")]
        public partial class OrangeHRMGoogleChromeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element1747682544Info;
            RepoItemInfo _orangehrmInfo;
            RepoItemInfo _element1614894656Info;

            /// <summary>
            /// Creates a new OrangeHRMGoogleChrome  folder.
            /// </summary>
            public OrangeHRMGoogleChromeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("OrangeHRMGoogleChrome", "/form[@title='OrangeHRM - Google Chrome']", parentFolder, 30000, null, true, "888a87c5-9591-4fea-86cc-f6151953c5a7", "")
            {
                _element1747682544Info = new RepoItemInfo(this, "Element1747682544", "element[@controlid='1747682544']", 30000, null, "94b8779b-30a7-49f9-a1b4-a9a05504a69c");
                _orangehrmInfo = new RepoItemInfo(this, "OrangeHRM", "container[@accessiblename~'^Continuous\\ Integration\\ wi']/container[@accessiblename='Google Chrome']//tabpage[@accessiblerole='PageTab' and @title='OrangeHRM' and @index='5']/text[@accessiblename='OrangeHRM']", 30000, null, "7f2ce0a5-e995-4b11-9c1d-6f090e932c1a");
                _element1614894656Info = new RepoItemInfo(this, "Element1614894656", "element[@controlid='1614894656']", 30000, null, "f783b13d-a554-4db0-ab39-ec684901d401");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("888a87c5-9591-4fea-86cc-f6151953c5a7")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("888a87c5-9591-4fea-86cc-f6151953c5a7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element1747682544 item.
            /// </summary>
            [RepositoryItem("94b8779b-30a7-49f9-a1b4-a9a05504a69c")]
            public virtual Ranorex.Unknown Element1747682544
            {
                get
                {
                    return _element1747682544Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element1747682544 item info.
            /// </summary>
            [RepositoryItemInfo("94b8779b-30a7-49f9-a1b4-a9a05504a69c")]
            public virtual RepoItemInfo Element1747682544Info
            {
                get
                {
                    return _element1747682544Info;
                }
            }

            /// <summary>
            /// The OrangeHRM item.
            /// </summary>
            [RepositoryItem("7f2ce0a5-e995-4b11-9c1d-6f090e932c1a")]
            public virtual Ranorex.Text OrangeHRM
            {
                get
                {
                    return _orangehrmInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The OrangeHRM item info.
            /// </summary>
            [RepositoryItemInfo("7f2ce0a5-e995-4b11-9c1d-6f090e932c1a")]
            public virtual RepoItemInfo OrangeHRMInfo
            {
                get
                {
                    return _orangehrmInfo;
                }
            }

            /// <summary>
            /// The Element1614894656 item.
            /// </summary>
            [RepositoryItem("f783b13d-a554-4db0-ab39-ec684901d401")]
            public virtual Ranorex.Unknown Element1614894656
            {
                get
                {
                    return _element1614894656Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element1614894656 item info.
            /// </summary>
            [RepositoryItemInfo("f783b13d-a554-4db0-ab39-ec684901d401")]
            public virtual RepoItemInfo Element1614894656Info
            {
                get
                {
                    return _element1614894656Info;
                }
            }
        }

        /// <summary>
        /// The DropdownAppFolder folder.
        /// </summary>
        [RepositoryFolder("75f53e42-e22e-422d-82c1-8ea4dd4b48d3")]
        public partial class DropdownAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new Dropdown  folder.
            /// </summary>
            public DropdownAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Dropdown", "/container[@caption='dropdown']", parentFolder, 30000, null, true, "75f53e42-e22e-422d-82c1-8ea4dd4b48d3", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("75f53e42-e22e-422d-82c1-8ea4dd4b48d3")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("75f53e42-e22e-422d-82c1-8ea4dd4b48d3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

        /// <summary>
        /// The HRManagementSystemOrangeHRMLHRMaAppFolder folder.
        /// </summary>
        [RepositoryFolder("c6feec1a-d49f-4fc7-9241-4e6d71d6e437")]
        public partial class HRManagementSystemOrangeHRMLHRMaAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _element1388912800Info;

            /// <summary>
            /// Creates a new HRManagementSystemOrangeHRMLHRMa  folder.
            /// </summary>
            public HRManagementSystemOrangeHRMLHRMaAppFolder(RepoGenBaseFolder parentFolder) :
                    base("HRManagementSystemOrangeHRMLHRMa", "/form[@title~'^HR\\ Management\\ System\\ \\|\\ Or']", parentFolder, 30000, null, true, "c6feec1a-d49f-4fc7-9241-4e6d71d6e437", "")
            {
                _element1388912800Info = new RepoItemInfo(this, "Element1388912800", "element[@controlid='-1388912800']", 30000, null, "7dfd2eed-df0e-4da7-b850-9bf4fc821fe8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("c6feec1a-d49f-4fc7-9241-4e6d71d6e437")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("c6feec1a-d49f-4fc7-9241-4e6d71d6e437")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Element1388912800 item.
            /// </summary>
            [RepositoryItem("7dfd2eed-df0e-4da7-b850-9bf4fc821fe8")]
            public virtual Ranorex.Unknown Element1388912800
            {
                get
                {
                    return _element1388912800Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The Element1388912800 item info.
            /// </summary>
            [RepositoryItemInfo("7dfd2eed-df0e-4da7-b850-9bf4fc821fe8")]
            public virtual RepoItemInfo Element1388912800Info
            {
                get
                {
                    return _element1388912800Info;
                }
            }
        }

    }
#pragma warning restore 0436
}